[toolchain]
channel = "stable"
targets = [
    "armv7-unknown-linux-musleabihf",  # Raspberry Pi (32-bit)
    "aarch64-unknown-linux-musl",  # Raspberry Pi (64-bit)
    "armv7-unknown-linux-gnueabihf",  # Raspberry Pi (32-bit)
    "aarch64-unknown-linux-gnu",  # Raspberry Pi (64-bit)
]